name: My App Manager Workflow

on:
  push:
    branches: [ "development" ]
env:
  BUNDLE_DIR: "app/build/outputs/bundle/release"
  APK_DIR: "app/build/outputs/apk/release"

jobs:

  build-apk-aab:
    env:
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      KEYSTORE_FILE_B64_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
    runs-on: ubuntu-latest
    steps:

      - name: checking out
        uses: actions/checkout@v3

      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: making gradlew executable
        run: chmod +x ./gradlew

      - name: Decode keystore b64 string to file
        run: |
          echo $KEYSTORE_FILE_B64_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Build release apk
        run: ./gradlew assembleRelease --stacktrace

      - name: Build release bundle
        run:  ./gradlew bundleRelease --stacktrace

      - name: Check release apk exist
        run: ls ${{env.APK_DIR}}/*apk

      - name: Check release aab exist
        run: ls ${{env.BUNDLE_DIR}}/*aab

      - name: Upload Apk as artifact
        uses: actions/upload-artifact@v4
        with:
          name: uda-apk
          path: ${{env.APK_DIR}}/app-release.apk

      - name: Upload Bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: uda-bundle
          path: ${{env.BUNDLE_DIR}}/app-release.aab

  deploy-firebase-app-distribution:
    runs-on: ubuntu-latest
    needs: build-apk-aab
    steps:

      - name: Download APK from artifact
        uses: actions/download-artifact@v4
        with:
          name: uda-apk
          path: ${{env.APK_DIR}}

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: ${{env.APK_DIR}}/app-release.apk

  deploy-googleplay:
    runs-on: ubuntu-latest
    needs: build-apk-aab
    steps:

      - name: Download Bundle from artifact
        uses: actions/download-artifact@v4
        with:
          name: uda-bundle
          path: ${{env.BUNDLE_DIR}}

      - name: Upload artifact to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.JSON_SERVICE_ACCOUNT_GOOGLE_PLAY }}
          packageName: com.kripto.myappmanager
          releaseFiles:  ${{env.BUNDLE_DIR}}/app-release.aab
          track: production